In [2]:
# %load cp_imports.py
%matplotlib inline
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
# Use retina backend for better figures
%config InlineBackend.figure_format = 'retina'


In [23]:
coefficient = np.array([[2, 1, 4, 1, -4], [3, 4, -1, -1, 3],
                        [1, -4, 1, 5, 9], [2, -2, 1, 3, 7]])

dimension = coefficient.shape[0]
varibles = np.zeros(dimension)
for i in range(dimension):
    coefficient[i] = coefficient[i] / coefficient[i, i]
    for j in range(i+1, dimension):
        coefficient[j] = coefficient[j] - coefficient[j, i] / coefficient[i, i] * coefficient[i]

# Solve xi in reverse order 
for i in range(-1, -dimension-1, -1):
    varibles[i] = coefficient[i, -1] - sum(coefficient[i, :-1] * varibles)

print(coefficient)
print(varibles)

[[ 1  0  2  0 -2]
 [ 0  1 -1  0  2]
 [ 0  0  1 -1 -3]
 [ 0  0  0  1  0]]
[ 4. -1. -3.  0.]


-1 0.0
-2 -3.0
-3 -1.0
